name: climatefinancebert_ui

services:
  climatefinancebert_ui:
    image: 'climatefinancebert_ui:latest'
    build:
      context: ./../
      dockerfile: docker/climatefinancebert_ui/Dockerfile
    ports: 
      - 8050:8050
    environment:
      - HOST=0.0.0.0  
      - PORT=8050     
    # env_file: ./../.env
    stdin_open: true  # Add this to make tty work properly
    tty: true
    restart: unless-stopped
