name: climatefinancebert_ui

services:
  climatefinancebert_ui:
    image: 'climatefinancebert_ui:latest'
    build:
      context: ./../
      dockerfile: docker/climatefinancebert_ui/Dockerfile
    volumes:
      - ./../data:/home/app/data
    ports: 
      - ${PORT:-8050}:${PORT:-8050}
    # env_file: 
    #   - ./../.env
    environment:
      - DEBUG=${DEBUG:-false}
      - HOST=0.0.0.0  # hard-coded for Docker, always use 0.0.0.0 regardless of .env
      - PORT=${PORT:-8050}     
    stdin_open: true  # Add this to make tty work properly
    tty: true
    restart: unless-stopped
