# Home page
INFOBOX = "infobox"
MAP = "map"
COUNTRIES_LAYER = "countries"
COLOR_LEGEND_CONTAINER = "color-legend-container"
COLOR_MODE_CONTAINER = "color-mode-container"
DATATABLE = "datatable"
DATATABLE_CARD = "datatable-card"
URL = "url"
PAGE_CONTENT = "page-content"
OPEN_FILTERS = "open-offcanvas"
## storage
STORED_DATA = "stored-data"
MODE_DATA = "mode-data"
RESET_MAP = "reset-map"
INITIAL_STATE = "initial-state"
STORED_GEOJSON = "stored-geojson"
## inputs
YEAR_SLIDER = "year_slider"
TYPE_DROPDOWN = "type_dropdown"
DONORTYPE_DROPDOWN = "donortype_dropdown"
CATEGORIES_DROPDOWN = "categories_dropdown"
CATEGORIES_SUB_DROPDOWN = "categories_sub_dropdown"
MAP_MODE = "map-mode"
COLOR_MODE = "color-mode"
## flow data
FLOW_DATA_BTN = "flow-data-btn"
FLOW_DATA_TABLE = "flow-data-table"
FLOW_DATA_MODAL = "flow-data-modal"
FLOW_TYPE_DROPDOWN = "flow-type-dropdown"

# Download page
QUERY_BTN = "query-btn"
DOWNLOAD_BTN = "download-btn"
DOWNLOAD_DATATABLE = "download-datatable"
DOWNLOAD_TRIGGER = "download-trigger"
DATATABLE_CARD_DOWNLOAD = "datatable-card-download"
## storage
DOWNLOAD_QUERIED_DATA = "download-queried-data"
## inputs
TYPE_DROPDOWN_DOWNLOAD = "type-dropdown-download"
YEAR_SLIDER_DOWNLOAD = "year-slider-download"
CATEGORIES_DROPDOWN_DOWNLOAD = "categories-dropdown-download"
CATEGORIES_SUB_DROPDOWN_DOWNLOAD = "categories-sub-dropdown-download"
DONORTYPE_DROPDOWN_DOWNLOAD = "donortype-dropdown-download"
FLOW_TYPE_DROPDOWN_DOWNLOAD = "flow-type-dropdown-download"
